### PR TITLE
Create _index.zh-hant.md

### PR DESCRIPTION
**Pull request by PikAsriel**
Traditional Chinese Translation

### CODE REVIEW

**Comment by veselle** [comment]
i cant read this

but it is outdated

the netescape link shouldnt be there anymore

**Comment by PikAsriel** [comment]
Fixed.

**Comment by veselle** [comment]
rad

also i need to update my discord username but ill do that eventually dw bout it

**Comment by veselle** [comment]
damn didnt realize config.toml had to be updated too

**Pull request merged**
